[CI][CK] Fix exported PATH to cover ROCM_PATH/bin directory
amd-smi call could generate an error due to binary/library mismatch:
AttributeError: .../libamd_smi.so: undefined symbol: amdsmi_set_gpu_clk_range.
                Did you mean: 'amdsmi_get_gpu_fan_rpms'?