Revert "use libc++ for old machines on gcc 7"
 breaks most epsdbs with error:

root@mlseqa-compcqe-aa-m3:~/aomp/test/smoke/clang-273739# /opt/rocm-5.3.0-10520/llvm//bin/clang++  -O2    -fopenmp -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx906  -D__OFFLOAD_ARCH_gfx906__ -stdlib=libc++ clang-273739.cpp -o clang-273739
In file included from <built-in>:1:
/opt/rocm-5.3.0-10520/llvm/lib/clang/16.0.0/include/openmp_wrappers/__clang_openmp_device_functions.h:53:10: fatal error: 'cstdint' file not found
         ^~~~~~~~~

This reverts commit 3ef9fcc2415d6a41888c007247b23bb7a1ff310b.